added solution for task 2 and 3
js-tasks-ru/js-20201030_ponomarevkonst pull request #6
Opened 2020-11-10 20:25 UTC by ponomarevkonst

2020-11-10 21:44 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- 03-objects-arrays-intro-to-testing/1-create-getter/index.spec.js — изменен
```

2020-11-11 00:15 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- 03-objects-arrays-intro-to-testing/1-create-getter/index.spec.js — изменен
```

2020-11-11 23:31 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return sorted.reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2020-11-11 23:31 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    path.split(".").forEach((element) => value = value[element]);
было бы неплохо вынести `path.split('.')` в родительскую функцию, иначе данная операция будет выполняться каждый раз при вызове геттера, хотя данное значение требуется рассчитать только один раз при создании геттера

2020-11-11 23:32 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.spec.js
> +});
нужно убрать эти изменения из PR

2020-11-11 23:32 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +  if (obj === undefined) {return undefined;}
мы не возвращаем явным образом с `undefined`, достаточно просто `return;`

2020-11-11 23:32 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +  let newObject = new Object();
подумайте, а точно ли здесь `let`?

2020-11-11 23:33 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2020-11-13 04:41 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
createGetter
+ should return existed properties
+ should return "undefined" for properties which does not exist
+ gets obj.property
+ returns undefined for no property
+ gets obj.nested.property
+ returns undefined for no nested.property
+ gets more.nested.property
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
trimSymbols
+ should remove an identical consecutive characters that exceed the specified size
+ should return empty string if it was passed to function like an argument
+ should return empty string if "size" equal 0
+ should return the same string if "size" parameter wasn't specified
```
```diff
invertObj
+ should swap keys and values and return new object
+ should return empty object if was passed object without values
+ should return "undefined" if object wasn't passed
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```
```diff
uniq
+ should return array with uniq values
+ should return empty array if was passed array without values
+ should return empty array if arguments wasn't passed
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-11-13 13:44 UTC, dosandk approved these changes

2020-11-13 13:45 UTC, merged